"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ClipboardCopy, Download, FileCheck2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { downloadBlob } from "@/lib/utils";

const checklists = [
  {
    slug: "scholarship",
    label: "Scholarship form",
    items: ["Photo in JPG format under the portal limit", "Signature cropped with no extra white space", "Income/caste/residence certificate PDF compressed", "Bank passbook or Aadhaar scan readable", "File names use simple English letters only"],
    tools: [["Photo resize", "/scholarship-photo-resize"], ["Signature resize", "/signature-resize"], ["Certificate compress", "/certificate-compress"]]
  },
  {
    slug: "exam",
    label: "Government exam form",
    items: ["Recent photo with clean background", "Signature on white paper, dark ink", "Photo and signature within required KB", "ID document scan readable", "Final file checked before submit"],
    tools: [["Admit card pack", "/admit-card-photo-signature"], ["Exam photo resize", "/exam-photo-resize"], ["AI checker", "/ai-file-checker"]]
  },
  {
    slug: "admission",
    label: "School/college admission",
    items: ["Student photo resized to portal dimensions", "Parent/student signature compressed", "Marksheet PDF under upload limit", "Certificate pages ordered correctly", "Mobile scan converted to PDF if needed"],
    tools: [["Admission pack", "/college-admission-photo-signature"], ["Document scanner", "/document-scanner"], ["PDF organizer", "/pdf-organize"]]
  },
  {
    slug: "job",
    label: "Job application",
    items: ["Profile photo square and professional", "Resume PDF under 500KB or 1MB", "Certificates compressed separately", "All PDFs open correctly after compression", "No password-protected files uploaded unless asked"],
    tools: [["Job photo resize", "/job-application-photo-resize"], ["Resume PDF compress", "/resume-pdf-compress"], ["PDF merge", "/pdf-merge"]]
  }
];

export function FormUploadChecklist() {
  const [slug, setSlug] = useState(checklists[1].slug);
  const [copied, setCopied] = useState(false);
  const checklist = useMemo(() => checklists.find((item) => item.slug === slug) ?? checklists[0], [slug]);
  const text = `${checklist.label} upload checklist\n\n${checklist.items.map((item, index) => `${index + 1}. ${item}`).join("\n")}\n\nGenerated by FormReady AI`;

  async function copyChecklist() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1400);
  }

  function downloadChecklist() {
    downloadBlob(new Blob([text], { type: "text/plain" }), `${checklist.slug}-upload-checklist.txt`);
  }

  return (
    <section className="container-page py-8">
      <div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-primary" />Form Upload Checklist</CardTitle>
            <CardDescription>Pick your form type and follow a clean pre-submit checklist before uploading files.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="space-y-2">
              <Label>Form type</Label>
              <Select value={slug} onChange={(event) => setSlug(event.target.value)}>
                {checklists.map((item) => <option key={item.slug} value={item.slug}>{item.label}</option>)}
              </Select>
            </div>
            <div className="rounded-2xl border bg-muted/20 p-4 text-sm leading-6 text-muted-foreground">
              Use this page as a last-step safety check. It reduces rejection caused by wrong format, wrong KB, unclear scans or broken file names.
            </div>
            <div className="flex flex-col gap-2 sm:flex-row">
              <Button className="flex-1" onClick={copyChecklist}><ClipboardCopy className="mr-2 h-4 w-4" />{copied ? "Copied" : "Copy checklist"}</Button>
              <Button className="flex-1" variant="secondary" onClick={downloadChecklist}><Download className="mr-2 h-4 w-4" />Download TXT</Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>{checklist.label}</CardTitle>
            <CardDescription>Recommended checks and direct tool links.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="grid gap-3">
              {checklist.items.map((item) => (
                <div key={item} className="flex gap-3 rounded-2xl border bg-background p-4 text-sm">
                  <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
            <div className="grid gap-3 sm:grid-cols-3">
              {checklist.tools.map(([label, href]) => (
                <Button key={href} asChild variant="secondary"><Link href={href}>{label}</Link></Button>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
