"use client";

import { useMemo, useState } from "react";
import { Archive, Download, Image as ImageIcon, Loader2, PenLine, Wand2, X } from "lucide-react";
import { UploadZone } from "@/components/upload-zone";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { photoPresets } from "@/lib/presets";
import { loadImage, resizeImageToBlob, trimWhitespace } from "@/lib/image";
import { cleanFileName, downloadBlob, formatBytes } from "@/lib/utils";

type OutputFile = { label: string; name: string; blob: Blob; before: number; after: number };

const signatureTargets = [10, 20, 50, 100];

export function PhotoSignaturePack() {
  const [presetSlug, setPresetSlug] = useState(photoPresets[1]?.slug ?? photoPresets[0].slug);
  const [photo, setPhoto] = useState<File | null>(null);
  const [signature, setSignature] = useState<File | null>(null);
  const [signatureKb, setSignatureKb] = useState(20);
  const [signatureWidth, setSignatureWidth] = useState(300);
  const [signatureHeight, setSignatureHeight] = useState(100);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [outputs, setOutputs] = useState<OutputFile[]>([]);

  const preset = useMemo(() => photoPresets.find((item) => item.slug === presetSlug) ?? photoPresets[0], [presetSlug]);

  function setSinglePhoto(files: File[]) {
    const file = files[0];
    setOutputs([]);
    setError("");
    if (!file) return;
    if (!file.type.startsWith("image/")) return setError("Upload a JPG, PNG or WebP photo.");
    setPhoto(file);
  }

  function setSingleSignature(files: File[]) {
    const file = files[0];
    setOutputs([]);
    setError("");
    if (!file) return;
    if (!file.type.startsWith("image/")) return setError("Upload a JPG, PNG or WebP signature image.");
    setSignature(file);
  }

  async function createPack() {
    if (!photo && !signature) return setError("Upload a photo or signature first.");
    setBusy(true);
    setError("");
    setOutputs([]);
    try {
      const next: OutputFile[] = [];
      if (photo) {
        const info = await loadImage(photo);
        const blob = await resizeImageToBlob(info.dataUrl, {
          width: preset.width ?? 300,
          height: preset.height ?? 400,
          targetKb: preset.maxKb,
          format: "image/jpeg",
          background: "white",
          zoom: 1,
          offsetX: 0,
          offsetY: 0
        });
        next.push({ label: `${preset.name} photo`, name: cleanFileName(photo.name, `${preset.slug}-photo`, "jpg"), blob, before: photo.size, after: blob.size });
      }
      if (signature) {
        const info = await loadImage(signature);
        const trimmed = await trimWhitespace(info.dataUrl);
        const blob = await resizeImageToBlob(trimmed, {
          width: signatureWidth,
          height: signatureHeight,
          targetKb: signatureKb,
          format: "image/jpeg",
          background: "white",
          zoom: 1,
          offsetX: 0,
          offsetY: 0
        });
        next.push({ label: "Signature", name: cleanFileName(signature.name, `signature-${signatureKb}kb`, "jpg"), blob, before: signature.size, after: blob.size });
      }
      setOutputs(next);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not create photo/signature pack.");
    } finally {
      setBusy(false);
    }
  }

  async function downloadZip() {
    if (!outputs.length) return;
    const { default: JSZip } = await import("jszip");
    const zip = new JSZip();
    outputs.forEach((item) => zip.file(item.name, item.blob));
    zip.file("readme.txt", "Generated by FormReady AI. Check official portal rules before final upload.");
    const blob = await zip.generateAsync({ type: "blob" });
    downloadBlob(blob, `formready-${preset.slug}-pack.zip`);
  }

  return (
    <section className="container-page py-8">
      <div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Archive className="h-5 w-5 text-primary" />Photo + Signature Pack Generator</CardTitle>
            <CardDescription>Create upload-ready photo and signature files together, then download separately or as one ZIP.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="space-y-2">
              <Label>Form preset</Label>
              <Select value={presetSlug} onChange={(event) => setPresetSlug(event.target.value)}>
                {photoPresets.map((item) => <option key={item.slug} value={item.slug}>{item.name} · {item.maxKb}KB</option>)}
              </Select>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <UploadZone accept="image/jpeg,image/png,image/webp" onFiles={setSinglePhoto} title="Upload photo" description={photo ? `${photo.name} · ${formatBytes(photo.size)}` : "JPG, PNG, WebP"} />
              <UploadZone accept="image/jpeg,image/png,image/webp" onFiles={setSingleSignature} title="Upload signature" description={signature ? `${signature.name} · ${formatBytes(signature.size)}` : "Cropped and cleaned automatically"} />
            </div>
            <div className="grid gap-3 rounded-2xl border p-4 sm:grid-cols-3">
              <div className="space-y-2"><Label>Signature KB</Label><Input type="number" min={5} value={signatureKb} onChange={(e) => setSignatureKb(Number(e.target.value))} /></div>
              <div className="space-y-2"><Label>Signature width</Label><Input type="number" min={80} value={signatureWidth} onChange={(e) => setSignatureWidth(Number(e.target.value))} /></div>
              <div className="space-y-2"><Label>Signature height</Label><Input type="number" min={40} value={signatureHeight} onChange={(e) => setSignatureHeight(Number(e.target.value))} /></div>
            </div>
            <div className="flex flex-wrap gap-2">{signatureTargets.map((kb) => <Button key={kb} type="button" size="sm" variant="secondary" onClick={() => setSignatureKb(kb)}>{kb}KB signature</Button>)}</div>
            {error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-600 dark:text-red-300">{error}</div>}
            <Button className="w-full" size="lg" onClick={createPack} disabled={busy}>{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}Create form-ready files</Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Output pack</CardTitle>
            <CardDescription>{preset.title}: {preset.width}×{preset.height}px, max {preset.maxKb}KB photo.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {!outputs.length && <div className="rounded-2xl border border-dashed bg-muted/20 p-8 text-center text-sm text-muted-foreground">Your fixed photo/signature files will appear here.</div>}
            {outputs.map((item) => (
              <div key={item.name} className="rounded-2xl border bg-muted/20 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="flex items-center gap-2 font-semibold">{item.label === "Signature" ? <PenLine className="h-4 w-4 text-primary" /> : <ImageIcon className="h-4 w-4 text-primary" />}{item.label}</div>
                    <p className="mt-1 text-xs text-muted-foreground">Before {formatBytes(item.before)} → After {formatBytes(item.after)}</p>
                  </div>
                  <Button size="sm" variant="ghost" onClick={() => setOutputs((prev) => prev.filter((out) => out.name !== item.name))}><X className="h-4 w-4" /></Button>
                </div>
                <Button className="mt-4 w-full" variant="secondary" onClick={() => downloadBlob(item.blob, item.name)}><Download className="mr-2 h-4 w-4" />Download {item.label.toLowerCase()}</Button>
              </div>
            ))}
            {outputs.length > 1 && <Button className="w-full" variant="dark" onClick={downloadZip}><Archive className="mr-2 h-4 w-4" />Download ZIP pack</Button>}
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
